version: 2
updates:
  - package-ecosystem: cargo
    directory: /CS2PlayerIntel-rs/src-tauri
    schedule:
      interval: weekly
    groups:
      tauri:
        patterns: ["tauri*"]
  - package-ecosystem: npm
    directory: /CS2PlayerIntel-rs
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
